version: '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: promomashdb
    ports:
      - "5555:5432"  
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d promomashdb"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  api:
    build:
      context: .  
      dockerfile: src/PromoMashTestTask.API/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=promomashdb;Username=postgres;Password=postgres
    networks:
      - app-network

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "4200:4200"  
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/dist  
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: